### ISSUE TITLE
JWT error

### ISSUE THREAD

**Issue by jillytot** [jillytot/remote-control#31]
node:30403) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (/home/soylentmail/remote-control/node_modules/jsonwebtoken/verify.js:63:1
7)
    at Promise (/home/soylentmail/remote-control/src/models/user.js:104:9)
    at new Promise (<anonymous>)
    at Object.module.exports.verifyAuthToken (/home/soylentmail/remote-control/src/models/user.js:102:28)
    at Socket.socket.on (/home/soylentmail/remote-control/src/events/index.js:19:32)
    at Socket.emit (events.js:197:13)
    at /home/soylentmail/remote-control/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
(node:30403) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin
g inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 (rejection id: 6)
undefined
(node:30403) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (/home/soylentmail/remote-control/node_modules/jsonwebtoken/verify.js:63:1
7)
    at Promise (/home/soylentmail/remote-control/src/models/user.js:104:9)
    at new Promise (<anonymous>)
    at module.exports.verifyAuthToken (/home/soylentmail/remote-control/src/models/user.js:102:28)
    at router.post (/home/soylentmail/remote-control/src/routes/api/auth.js:5:25)
    at Layer.handle [as handle_request] (/home/soylentmail/remote-control/node_modules/express/lib/router/layer.js:
95:5)
    at next (/home/soylentmail/remote-control/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/soylentmail/remote-control/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/soylentmail/remote-control/node_modules/express/lib/router/layer.js:
95:5)
    at /home/soylentmail/remote-control/node_modules/express/lib/router/index.js:281:22
(node:30403) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin
g inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 (rejection id: 8)

**Comment by jillytot** [comment]
This is possibly caused by having a JWT token cached by the client, will need to investigate.

**Comment by jillytot** [comment]
I can now confirm the token is getting verified / extracted correctly, however.... 

```
API/AUTH: Verify User:  user-7b2b8204-4650-4397-87d1-f83bd39ce339
Verifying Auth Token
Check Token:  { id: 'user-7b2b8204-4650-4397-87d1-f83bd39ce339',
  iat: 1558645147,
  exp: 1561237147,
  sub: '' }
API/AUTH: Verify User:  user-7b2b8204-4650-4397-87d1-f83bd39ce339
Verifying Auth Token
(node:5823) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (/home/soylentmail/remote-control/node_modules/jsonwebtoken/verify.js:63:17)
    at Promise (/home/soylentmail/remote-control/src/models/user.js:121:9)
    at new Promise (<anonymous>)
    at module.exports.verifyAuthToken (/home/soylentmail/remote-control/src/models/user.js:120:28)
    at router.post (/home/soylentmail/remote-control/src/routes/api/auth.js:5:25)
    at Layer.handle [as handle_request] (/home/soylentmail/remote-control/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/soylentmail/remote-control/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/soylentmail/remote-control/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/soylentmail/remote-control/node_modules/express/lib/router/layer.js:95:5)
    at /home/soylentmail/remote-control/node_modules/express/lib/router/index.js:281:22
(node:5823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 60)
```

**Comment by jillytot** [comment]
donzo!
